var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(staff)/students/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__90c6e637._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_e430d5bb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4ba7cd72._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9ff09347._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/[root-of-the-server]__389530a9._.js")
R.c("server/chunks/ssr/_3d073465._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(staff)_students_page_actions_cc3eef42.js")
R.m(67111)
module.exports=R.m(67111).exports
