// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(admin)/attendance-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance-management">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/attendance-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certificates">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contracts">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/finance-users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-users">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/finance-users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/permissions">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/registrars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registrars">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/registrars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teachers">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/audit">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/expenses">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/partners">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/reports">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/student-fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/student-fees">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/student-fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/finance/teacher-payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/teacher-payroll">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/finance/teacher-payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(staff)/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/students">> = Specific
  const handler = {} as typeof import("../../../app/(staff)/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(teacher)/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../../app/(teacher)/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../../app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/classes/[id]/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/classes/[id]/students">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/classes/[id]/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/classes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/classes">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/classes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/history">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/records/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/records">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/records/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/export">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/certificates/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/certificates/send">> = Specific
  const handler = {} as typeof import("../../../app/api/certificates/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/classes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/classes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/classes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classes">> = Specific
  const handler = {} as typeof import("../../../app/api/classes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contracts/[id]/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]/payouts">> = Specific
  const handler = {} as typeof import("../../../app/api/contracts/[id]/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contracts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/contracts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contracts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contracts">> = Specific
  const handler = {} as typeof import("../../../app/api/contracts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/courses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/courses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses">> = Specific
  const handler = {} as typeof import("../../../app/api/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/archive-attendance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/archive-attendance">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/archive-attendance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/visit-reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/visit-reminders">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/visit-reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/activities">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance-users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance-users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/finance-users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance-users">> = Specific
  const handler = {} as typeof import("../../../app/api/finance-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/entries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/entries">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/entries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/reports/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/reports/export">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/reports/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/summary/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/summary/export">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/summary/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/finance/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/finance/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/email/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/email/broadcast">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/email/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/email/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/email/logs">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/email/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/email/single/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/email/single">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/email/single/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/sms/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/sms/broadcast">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/sms/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/sms/single/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/sms/single">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/sms/single/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/whatsapp/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/whatsapp/broadcast">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/whatsapp/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/whatsapp/single/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/whatsapp/single">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/whatsapp/single/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partners/[id]/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]/payouts">> = Specific
  const handler = {} as typeof import("../../../app/api/partners/[id]/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partners/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/partners/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners">> = Specific
  const handler = {} as typeof import("../../../app/api/partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/permissions">> = Specific
  const handler = {} as typeof import("../../../app/api/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/registrars/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registrars/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/registrars/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/registrars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registrars">> = Specific
  const handler = {} as typeof import("../../../app/api/registrars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/download/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/download/pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/download/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/download">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/overview/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/overview/export">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/overview/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/shifts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/shifts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts">> = Specific
  const handler = {} as typeof import("../../../app/api/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/staff/[id]/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/[id]/payouts">> = Specific
  const handler = {} as typeof import("../../../app/api/staff/[id]/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/staff/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/staff/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff">> = Specific
  const handler = {} as typeof import("../../../app/api/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/students/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/students/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students">> = Specific
  const handler = {} as typeof import("../../../app/api/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/teachers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teachers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/teachers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/teachers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/teachers">> = Specific
  const handler = {} as typeof import("../../../app/api/teachers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(finance)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(finance)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(staff)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(staff)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(teacher)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(teacher)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
