var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(finance)/finance/expenses/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9eba8f08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_e52f5964._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4ba7cd72._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9ff09347._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/[root-of-the-server]__f24d670c._.js")
R.c("server/chunks/ssr/_3d073465._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(finance)_finance_expenses_page_actions_23d428df.js")
R.m(12969)
module.exports=R.m(12969).exports
