// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/attendance" | "/attendance-management" | "/audit" | "/certificates" | "/classes" | "/contracts" | "/courses" | "/dashboard" | "/finance" | "/finance-users" | "/finance/audit" | "/finance/expenses" | "/finance/partners" | "/finance/reports" | "/finance/student-fees" | "/finance/teacher-payroll" | "/forgot-password" | "/login" | "/messages" | "/partners" | "/payments" | "/permissions" | "/registrars" | "/reports" | "/reset-password" | "/students" | "/teachers" | "/unauthorized"
type AppRouteHandlerRoutes = "/api/attendance" | "/api/attendance/classes" | "/api/attendance/classes/[id]/students" | "/api/attendance/history" | "/api/attendance/records" | "/api/attendance/summary" | "/api/audit" | "/api/audit/export" | "/api/auth/change-password" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/reset-password" | "/api/certificates/send" | "/api/classes" | "/api/classes/[id]" | "/api/contracts" | "/api/contracts/[id]" | "/api/contracts/[id]/payouts" | "/api/courses" | "/api/courses/[id]" | "/api/cron/archive-attendance" | "/api/cron/visit-reminders" | "/api/dashboard/activities" | "/api/finance-users" | "/api/finance-users/[id]" | "/api/finance/entries" | "/api/finance/reports" | "/api/finance/reports/export" | "/api/finance/summary" | "/api/finance/summary/export" | "/api/notifications/email/broadcast" | "/api/notifications/email/logs" | "/api/notifications/email/single" | "/api/notifications/sms/broadcast" | "/api/notifications/sms/single" | "/api/notifications/whatsapp/broadcast" | "/api/notifications/whatsapp/single" | "/api/partners" | "/api/partners/[id]" | "/api/partners/[id]/payouts" | "/api/payments" | "/api/payments/summary" | "/api/permissions" | "/api/registrars" | "/api/registrars/[id]" | "/api/reports/download" | "/api/reports/download/pdf" | "/api/reports/overview" | "/api/reports/overview/export" | "/api/reports/summary" | "/api/shifts" | "/api/shifts/[id]" | "/api/staff" | "/api/staff/[id]" | "/api/staff/[id]/payouts" | "/api/students" | "/api/students/[id]" | "/api/teachers" | "/api/teachers/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/attendance": {}
  "/api/attendance/classes": {}
  "/api/attendance/classes/[id]/students": { "id": string; }
  "/api/attendance/history": {}
  "/api/attendance/records": {}
  "/api/attendance/summary": {}
  "/api/audit": {}
  "/api/audit/export": {}
  "/api/auth/change-password": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/reset-password": {}
  "/api/certificates/send": {}
  "/api/classes": {}
  "/api/classes/[id]": { "id": string; }
  "/api/contracts": {}
  "/api/contracts/[id]": { "id": string; }
  "/api/contracts/[id]/payouts": { "id": string; }
  "/api/courses": {}
  "/api/courses/[id]": { "id": string; }
  "/api/cron/archive-attendance": {}
  "/api/cron/visit-reminders": {}
  "/api/dashboard/activities": {}
  "/api/finance-users": {}
  "/api/finance-users/[id]": { "id": string; }
  "/api/finance/entries": {}
  "/api/finance/reports": {}
  "/api/finance/reports/export": {}
  "/api/finance/summary": {}
  "/api/finance/summary/export": {}
  "/api/notifications/email/broadcast": {}
  "/api/notifications/email/logs": {}
  "/api/notifications/email/single": {}
  "/api/notifications/sms/broadcast": {}
  "/api/notifications/sms/single": {}
  "/api/notifications/whatsapp/broadcast": {}
  "/api/notifications/whatsapp/single": {}
  "/api/partners": {}
  "/api/partners/[id]": { "id": string; }
  "/api/partners/[id]/payouts": { "id": string; }
  "/api/payments": {}
  "/api/payments/summary": {}
  "/api/permissions": {}
  "/api/registrars": {}
  "/api/registrars/[id]": { "id": string; }
  "/api/reports/download": {}
  "/api/reports/download/pdf": {}
  "/api/reports/overview": {}
  "/api/reports/overview/export": {}
  "/api/reports/summary": {}
  "/api/shifts": {}
  "/api/shifts/[id]": { "id": string; }
  "/api/staff": {}
  "/api/staff/[id]": { "id": string; }
  "/api/staff/[id]/payouts": { "id": string; }
  "/api/students": {}
  "/api/students/[id]": { "id": string; }
  "/api/teachers": {}
  "/api/teachers/[id]": { "id": string; }
  "/attendance": {}
  "/attendance-management": {}
  "/audit": {}
  "/certificates": {}
  "/classes": {}
  "/contracts": {}
  "/courses": {}
  "/dashboard": {}
  "/finance": {}
  "/finance-users": {}
  "/finance/audit": {}
  "/finance/expenses": {}
  "/finance/partners": {}
  "/finance/reports": {}
  "/finance/student-fees": {}
  "/finance/teacher-payroll": {}
  "/forgot-password": {}
  "/login": {}
  "/messages": {}
  "/partners": {}
  "/payments": {}
  "/permissions": {}
  "/registrars": {}
  "/reports": {}
  "/reset-password": {}
  "/students": {}
  "/teachers": {}
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
